### ISSUE TITLE
PIO library dependencies include error

### ISSUE THREAD

**Issue by Vict0rAH** [pierremolinaro/acan-t4#1]
Hi,
I hope you can help me with an issue concerning including the ACAN_T4 library in PlatformIO.
Long story short, I am working on a project with two boards, a Teensy 3.6 and 4.0. I am therefore using both your ACAN.h library and your ACAN_T4.h library. My issue is that PIO doesn't seem to find the ACAN_T4. I've worked in a while with the 3.6 board and ACAN.h with no problems at all, but with ACAN_T4, I am asked to update my include path, even though I have the library in my library dependencies.
I've tried to make a seperate project with only the 4.0 environment in my .ini file, and only including the pierremolinaro/ACAN_T4 @ ^1.1.1 in my library dependencies, but PIO fails to recognize it.

I'm aware this might be a long shot, but none the less, I was wondering if you know a way to fix this issue?
Thanks in advance.

**Comment by Vict0rAH** [comment]
Turns out it was a problem between PIO and vscode json file

**Comment by pierremolinaro** [comment]
Ok, I couldn't have helped you, because I don't know PlatformIO.

Regards,

Pierre Molinaro
