### ISSUE TITLE
ACAN_T4::can3.transmitErrorCounter() in CANFD?

### ISSUE THREAD

**Issue by syrinxtech** [pierremolinaro/acan-t4#9]
Pierre,

I've been using the library for a while now and had been using `ACAN_T4::can3.transmitErrorCounter()` in my code.  Since I upgraded to the current version, I'm getting a lot of **Transmit EC: 97** in my logs.  This log entry represents the error code from the previously mentioned function call immediately after a `ACAN_T4::can3.tryToSendReturnStatusFD()` call.  I wasn't getting any error codes from the previous version of the library.  I looked in the manual and didn't see a reference to this function call in the CANFD section, only the CAN 2.0B section.  Is this call valid in CANFD?

One more thing, any idea what the number represents?  It's not the same all the time.  It seems to start at some number, count down for a number of packets, then disappear, only to reappear later with a different starting number.

Thanks, 
Bryan

**Comment by pierremolinaro** [comment]
Hello Bryan,

I have forgotten this function in the documentation, it is available for CANFD.

Do you use CAN FD frame with bit rate switch ? If not, the timing constraints are the same as CAN 2.0B, even if you use CAN FD frame without bit rate switch. So the Transmit EC should have the same behaviour as in CAN 2.0B.

If yes :
	- what is the CAN FD transceiver you use ? 
	- check the data bit rate decomposition ; it is tricky, but bit rate switching requires the sample point to be as close as possible on all CAN FD controllers. If your network contains only Teensy 4.x with the same ACAN_T4 settings, of course it is ok, the sample points are equal. If you have different controllers, this should be checked. The function dataSamplePointFromBitStart returns the value in per-cent.

Best Regards,

Pierre

**Comment by syrinxtech** [comment]
Pierrre,

Yes, I do use bit rate switch (1Mbps/5Mbps).  I'm using two Teensy 4.0's and one Teensy 4.1, all with the Adafruit NXP TJA1051T/3 CANBus transceiver.  All 3 Teensy's are configured identically.  I think I may have had something weird in my code, because I recompiled and those weird error count messages disappeared.  False alarm I guess.

Thanks for the quick response.
